version: '3.8'

services:
  web:
    build: ./nextbnb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./nextbnb:/usr/src/nextbnb
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db  
  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser 
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=nextbnb  

volumes:
  postgres-data:      
